In [ ]:
#Create Model Class
import torch
import torch.nn as nn # contains neural network components ex- nn.Linear nn.Conv2d nn.Sogmoid nn.Relu nn.CrossEntropyLoss

class model(nn.Module): # All pytorch model must inherit from this class so that pytorch can manage your network
  def __init__(self,num_feature): #this run when model is created
    super().__init__() # initialize the nn.module parent class
    self.linear = nn.Linear(num_feature,1) #  input size =  num_feature and output size = 1 # weight shape = (1, num_feature) is how it's STORED
# but the actual matmul is (batch_size, num_feature) @ (num_feature, 1) → (batch_size, 1)) bias  shape = (1)
    self.sigmoid = nn.Sigmoid() #Because we are using binary classification
  def forward(self,feature): # forwardpropagation function
    out = self.linear(feature) # feature shape = (batch_size, num_feature)
# weight stored as (1, num_feature), transposed to (num_feature, 1) during matmul
# result = (batch_size, 1)
    out = self.sigmoid(out)  # Sigmoid function is used  for activation

    return out # return the final prediction




In [ ]:
#create dataset
feature = torch.rand(10,5)

#create model
model = model(feature.shape[1])

#call model for forward pass
model(feature)

tensor([[0.5441],
        [0.5705],
        [0.5224],
        [0.5107],
        [0.5746],
        [0.5273],
        [0.5629],
        [0.4918],
        [0.5759],
        [0.5045]], grad_fn=<SigmoidBackward0>)

In [ ]:
#show model weight
model.linear.weight

Parameter containing:
tensor([[-0.3231,  0.0629, -0.1414,  0.1106,  0.1121]], requires_grad=True)

In [ ]:
#show model bias
model.linear.bias

Parameter containing:
tensor([0.2349], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model,input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00